version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install --upgrade pip
      - python -m pip install mkdocs

      - python --version
      - pip --version
      - mkdocs --version
  build:
    commands:
      - python -m mkdocs build
  post_build:
    commands:
      - aws s3 rm --recursive s3://$S3_BUCKET
      - aws s3 cp ./site s3://$S3_BUCKET --recursive
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
